In [1]:
print("helo")

helo


In [2]:
import numpy as np
arr1 = [1, 2, 3]
print("Arr1 multiplication ; ", arr1 * 2)

arr2 = np.array([1, 2, 3])
print("Arr2 NP mult : ", arr2 * 2)

Arr1 multiplication ;  [1, 2, 3, 1, 2, 3]
Arr2 NP mult :  [2 4 6]


In [17]:

nums1 = np.full((3, 9), 8)
print(nums1)

nums2 = np.full((9, 6), 3)
print(nums2)

result = nums1 @ nums2  # shape (3, 6)
print(result)


[[8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8]]
[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]
[[216 216 216 216 216 216]
 [216 216 216 216 216 216]
 [216 216 216 216 216 216]]
